### ISSUE TITLE
Javascript error apparently involving update logic

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#370]
User ddden reports this error:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Object has been destroyed
at MacUpdater.eval (webpack-internal:///32:1206:13)
at MacUpdater.emit (events.js:210:5)
at MacUpdater.dispatchUpdateDownloaded (/Applications/Zbay.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:439:10)
at AutoUpdater.<anonymous> (/Applications/Zbay.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:26:12)
at AutoUpdater.emit (events.js:210:5)
```

They also report a failed message. @NorbertBodziony thoughts?

**Comment by jkdev601** [comment]
@holmesworcester, we are using setInterval method for checking if there is new update available, but leaving Zbay in sleeping mode causes that the update checking function is called more then once. We should use setTImeout instead of setInterval to resolve above.

**Comment by holmesworcester** [comment]
great. let’s fix soon!
