### ISSUE TITLE
ZbayLite still throws javascript error repeatedly

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#403]
```
Uncaught Exception:
Error: ENOENT: no such file or directory, stat '/Users/holmes/Library/Application Support/ZbayData/zbayMainnet'
    at statSync (fs.js:915:3)
    at Object.fs.statSync (electron/js2c/asar.js:278:27)
    at Object.statSync (/Applications/Zbay-lite.app/Contents/Resources/app.asar/node_modules/fs-extra/node_modules/graceful-fs/polyfills.js:307:34)
    at getStatsSync (/Applications/Zbay-lite.app/Contents/Resources/app.asar/node_modules/fs-extra/lib/util/stat.js:58:18)
    at Object.checkPathsSync (/Applications/Zbay-lite.app/Contents/Resources/app.asar/node_modules/fs-extra/lib/util/stat.js:90:33)
    at Object.copySync (/Applications/Zbay-lite.app/Contents/Resources/app.asar/node_modules/fs-extra/lib/copy-sync/copy-sync.js:24:38)
    at Object.makeWalletCopy (webpack-internal:///27:240:33)
    at IpcMainImpl.eval (webpack-internal:///27:1032:13)
    at IpcMainImpl.emit (events.js:210:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3908:15)
```

**Comment by holmesworcester** [comment]
This error is happening regularly. Just running as a normal user on Mac. My data files were created in an older version of ZbayLite.

**Comment by kingalg** [comment]
It didn't happened to me for the last 2 weeks in any situation that previously triggered those errors.
