### ISSUE TITLE
Javascript error, possibly related to loss of network or wake from sleep.

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#736]
I saw this when I returned to Zbay after some time. 

I think it happened due to sleep or the network going down.

```
Uncaught Exception:
Error: net::ERR_NAME_NOT_RESOLVED
at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
at SimpleURLLoaderWrapper.emit (events.js:210:5)
From previous event:
at GenericProvider.getLatestVersion (/Applications/Zbay 323.app/Contents/Resources/app.asar/node_modules/electron-updater/src/providers/GenericProvider.ts:18:25)
at /Applications/Zbay 323.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:347:26
at Generator.next (<anonymous>)
at processImmediate (internal/timers.js:439:21)
From previous event:
at MacUpdater.getUpdateInfoAndProvider (/Applications/Zbay 323.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:336:43)
at /Applications/Zbay 323.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:363:31
at Generator.next (<anonymous>)
From previous event:
at MacUpdater.doCheckForUpdates (/Applications/Zbay 323.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
at MacUpdater.checkForUpdates (/Applications/Zbay 323.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
at Object.exports.checkForUpdate (/Applications/Zbay 323.app/Contents/Resources/app.asar/dist/main/main.js:252:36)
at Timeout._onTimeout (/Applications/Zbay 323.app/Contents/Resources/app.asar/dist/main/main.js:388:49)
at listOnTimeout (internal/timers.js:531:17)
at processTimers (internal/timers.js:475:7)
```

**Comment by vinkabuki** [comment]
possibly related to:
![Uploading Screenshot 2021-03-30 at 11.58.01.png…]()

**Comment by kingalg** [comment]
This error is still happening in a new version. Text of an error is diferent but logic behind is the same - internet was dissconected when computer was on sleep mode. Happens on both systems.

![image](https://user-images.githubusercontent.com/68909168/113990714-072c0e00-9852-11eb-8c53-10ad2f85f4dd.png)

**Comment by vinkabuki** [comment]
fixed, but do not close this thread, since there may be other errors from this 'family', I have to explicitly tell zbay to catch them

**Comment by holmesworcester** [comment]
@vinkabuki I just got this error, after wake from sleep.

```
Uncaught Exception:
Error: net::ERR_NAME_NOT_RESOLVED
at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2568:21)
at SimpleURLLoaderWrapper.emit (events.js:210:5)
From previous event:
at GenericProvider.getLatestVersion (/Applications/Zbay.app/Contents/Resources/app.asar/node_modules/electron-updater/src/providers/GenericProvider.ts:18:25)
at /Applications/Zbay.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:347:26
at Generator.next (<anonymous>)
at processImmediate (internal/timers.js:439:21)
From previous event:
at MacUpdater.getUpdateInfoAndProvider (/Applications/Zbay.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:336:43)
at /Applications/Zbay.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:363:31
at Generator.next (<anonymous>)
From previous event:
at MacUpdater.doCheckForUpdates (/Applications/Zbay.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
at MacUpdater.checkForUpdates (/Applications/Zbay.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
at Object.exports.checkForUpdate (/Applications/Zbay.app/Contents/Resources/app.asar/dist/main/main.js:271:40)
at Timeout._onTimeout (/Applications/Zbay.app/Contents/Resources/app.asar/dist/main/main.js:417:49)
at listOnTimeout (internal/timers.js:531:17)
at processTimers (internal/timers.js:475:7)
```
