### ISSUE TITLE
Zbay does not completely shut down on Windows (formerly: user can see notifications from zbay after closing zbay)

### ISSUE THREAD

**Issue by kingalg** [ZbayApp/zbay#763]
If the user opens Zbay and closes it after a short time (before seeing all notifications that he missed when he wasn't logged in) notifications appear for him even after closing an app.

System: Windows

Steps to recreate:
1. Use user on Zbay for which there will be some notifications once he log in
2. Open Zbay
3. Close Zbay as soon as possible
4. Notifications should stop appearing after the app is closed but right now the user receives them even after closing an app.

**Comment by holmesworcester** [comment]
I think this is happening because there are processes that keep running in the background on Windows when Zbay is closed. A user reported seeing this problem. There's no user-facing indication that anything is running on Windows, but there are still multiple Zbay processes visible when you check.

**Comment by holmesworcester** [comment]
So first, there seem to be a bunch of errors.

<img width="736" alt="image" src="https://user-images.githubusercontent.com/213678/117548137-3c6a7e00-b001-11eb-8142-55e52ee4e235.png">

But I was able to fetch some recent messages, at least in one attempt.

<img width="805" alt="image" src="https://user-images.githubusercontent.com/213678/117548152-5906b600-b001-11eb-911d-36b8fe8a1b47.png">

Sure enough, on quit, the app appears to shut down and is no longer visible in the bottom bar, but 4 processes are still running.

<img width="1331" alt="image" src="https://user-images.githubusercontent.com/213678/117548182-8fdccc00-b001-11eb-924d-5c8b3ac57a2c.png">

I checked quickly to see if there are any recent fixes in the Electron project that mention this (https://www.electronjs.org/releases/stable). There was one that had something to do with a closed window (https://github.com/electron/electron/pull/28913) but it doesn't seem like the issue. We should update electron anyway and I'll try this. 

Notably, lots of stuff doesn't seem to work at all in Zbay. The Zcash stuff simply breaks, or appears to. This might be an issue with the VM I'm using, but I gave it 8GB of ram so it should be okay? 

Another error:

<img width="573" alt="image" src="https://user-images.githubusercontent.com/213678/117548283-25785b80-b002-11eb-9946-f77e877ee4e5.png">

There's an unrelated bug where the old welcome message displays on Windows:

<img width="788" alt="image" src="https://user-images.githubusercontent.com/213678/117548339-72f4c880-b002-11eb-9d9a-e8065e667d67.png">

It looks like waggle is connected but I am not able to send messages. When I hit enter my message disappears. There were some errors in the logs on startup.

```
PS C:\Users\IEUser\AppData\Local\Programs\zbay> .\Zbay.exe
PS C:\Users\IEUser\AppData\Local\Programs\zbay> 
creatd windows
before spawning tor
received signal
<ref *1> Socket {
  connecting: true,
  _hadError: false,
  _parent: null,
  _host: 'localhost',
  _readableState: ReadableState {
    objectMode: false,
    highWaterMark: 16384,
    buffer: BufferList { head: null, tail: null, length: 0 },
    length: 0,
    pipes: [],
    flowing: null,
    ended: false,
    endEmitted: false,
    reading: false,
    sync: true,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    errorEmitted: false,
    emitClose: false,
    autoDestroy: false,
    destroyed: false,
    errored: null,
    closed: false,
    closeEmitted: false,
    defaultEncoding: 'utf8',
    awaitDrainWriters: null,
    multiAwaitDrain: false,
    readingMore: false,
    decoder: null,
    encoding: null,
    [Symbol(kPaused)]: null
  },
  _events: [Object: null prototype] { end: [Function: onReadableStreamEnd] },
  _eventsCount: 1,
  _maxListeners: undefined,
  _writableState: WritableState {
    objectMode: false,
    highWaterMark: 16384,
    finalCalled: false,
    needDrain: false,
    ending: false,
    ended: false,
    finished: false,
    destroyed: false,
    decodeStrings: false,
    defaultEncoding: 'utf8',
    length: 0,
    writing: false,
    corked: 0,
    sync: true,
    bufferProcessing: false,
    onwrite: [Function: bound onwrite],
    writecb: null,
    writelen: 0,
    afterWriteTickInfo: null,
    buffered: [],
    bufferedIndex: 0,
    allBuffers: true,
    allNoop: true,
    pendingcb: 0,
    prefinished: false,
    errorEmitted: false,
    emitClose: false,
    autoDestroy: false,
    errored: null,
    closed: false,
    closeEmitted: false,
    writable: true
  },
  allowHalfOpen: false,
  _sockname: null,
  _pendingData: null,
  _pendingEncoding: '',
  server: null,
  _server: null,
  [Symbol(async_id_symbol)]: 51,
  [Symbol(kHandle)]: TCP {
    reading: false,
    onconnection: null,
    [Symbol(owner_symbol)]: [Circular *1]
  },
  [Symbol(kSetNoDelay)]: false,
  [Symbol(lastWriteQueueSize)]: 0,
  [Symbol(timeout)]: null,
  [Symbol(kBuffer)]: null,
  [Symbol(kBufferCb)]: null,
  [Symbol(kBufferGen)]: null,
  [Symbol(kCapture)]: false,
  [Symbol(kBytesRead)]: 0,
  [Symbol(kBytesWritten)]: 0
}
error connecting
entered this.connect
reveived error inside this.connect
Error: Error connecting to control port: Error: connect ECONNREFUSED 127.0.0.1:9151
    at Socket.<anonymous> (C:\Users\IEUser\AppData\Local\Programs\zbay\resources\app.asar\node_modules\waggle\lib\torManager\torControl.js:94:24)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
error connecting
received signal
<ref *1> Socket {
  connecting: true,
  _hadError: false,
  _parent: null,
  _host: 'localhost',
  _readableState: ReadableState {
    objectMode: false,
    highWaterMark: 16384,
    buffer: BufferList { head: null, tail: null, length: 0 },
    length: 0,
    pipes: [],
    flowing: null,
    ended: false,
    endEmitted: false,
    reading: false,
    sync: true,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    errorEmitted: false,
    emitClose: false,
    autoDestroy: false,
    destroyed: false,
    errored: null,
    closed: false,
    closeEmitted: false,
    defaultEncoding: 'utf8',
    awaitDrainWriters: null,
    multiAwaitDrain: false,
    readingMore: false,
    decoder: null,
    encoding: null,
    [Symbol(kPaused)]: null
  },
  _events: [Object: null prototype] { end: [Function: onReadableStreamEnd] },
  _eventsCount: 1,
  _maxListeners: undefined,
  _writableState: WritableState {
    objectMode: false,
    highWaterMark: 16384,
    finalCalled: false,
    needDrain: false,
    ending: false,
    ended: false,
    finished: false,
    destroyed: false,
    decodeStrings: false,
    defaultEncoding: 'utf8',
    length: 0,
    writing: false,
    corked: 0,
    sync: true,
    bufferProcessing: false,
    onwrite: [Function: bound onwrite],
    writecb: null,
    writelen: 0,
    afterWriteTickInfo: null,
    buffered: [],
    bufferedIndex: 0,
    allBuffers: true,
    allNoop: true,
    pendingcb: 0,
    prefinished: false,
    errorEmitted: false,
    emitClose: false,
    autoDestroy: false,
    errored: null,
    closed: false,
    closeEmitted: false,
    writable: true
  },
  allowHalfOpen: false,
  _sockname: null,
  _pendingData: null,
  _pendingEncoding: '',
  server: null,
  _server: null,
  [Symbol(async_id_symbol)]: 72,
  [Symbol(kHandle)]: TCP {
    reading: false,
    onconnection: null,
    [Symbol(owner_symbol)]: [Circular *1]
  },
  [Symbol(kSetNoDelay)]: false,
  [Symbol(lastWriteQueueSize)]: 0,
  [Symbol(timeout)]: null,
  [Symbol(kBuffer)]: null,
  [Symbol(kBufferCb)]: null,
  [Symbol(kBufferGen)]: null,
  [Symbol(kCapture)]: false,
  [Symbol(kBytesRead)]: 0,
  [Symbol(kBytesWritten)]: 0
}
data is 250 OK

entered this.connect
data is 250 OK

data is 250 closing connection

connection ended
dataaa 250 OK

outside conditional
outside conditional
<ref *1> Socket {
  connecting: true,
  _hadError: false,
  _parent: null,
  _host: 'localhost',
  _readableState: ReadableState {
    objectMode: false,
    highWaterMark: 16384,
    buffer: BufferList { head: null, tail: null, length: 0 },
    length: 0,
    pipes: [],
    flowing: null,
    ended: false,
    endEmitted: false,
    reading: false,
    sync: true,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    errorEmitted: false,
    emitClose: false,
    autoDestroy: false,
    destroyed: false,
    errored: null,
    closed: false,
    closeEmitted: false,
    defaultEncoding: 'utf8',
    awaitDrainWriters: null,
    multiAwaitDrain: false,
    readingMore: false,
    decoder: null,
    encoding: null,
    [Symbol(kPaused)]: null
  },
  _events: [Object: null prototype] { end: [Function: onReadableStreamEnd] },
  _eventsCount: 1,
  _maxListeners: undefined,
  _writableState: WritableState {
    objectMode: false,
    highWaterMark: 16384,
    finalCalled: false,
    needDrain: false,
    ending: false,
    ended: false,
    finished: false,
    destroyed: false,
    decodeStrings: false,
    defaultEncoding: 'utf8',
    length: 0,
    writing: false,
    corked: 0,
    sync: true,
    bufferProcessing: false,
    onwrite: [Function: bound onwrite],
    writecb: null,
    writelen: 0,
    afterWriteTickInfo: null,
    buffered: [],
    bufferedIndex: 0,
    allBuffers: true,
    allNoop: true,
    pendingcb: 0,
    prefinished: false,
    errorEmitted: false,
    emitClose: false,
    autoDestroy: false,
    errored: null,
    closed: false,
    closeEmitted: false,
    writable: true
  },
  allowHalfOpen: false,
  _sockname: null,
  _pendingData: null,
  _pendingEncoding: '',
  server: null,
  _server: null,
  [Symbol(async_id_symbol)]: 90,
  [Symbol(kHandle)]: TCP {
    reading: false,
    onconnection: null,
    [Symbol(owner_symbol)]: [Circular *1]
  },
  [Symbol(kSetNoDelay)]: false,
  [Symbol(lastWriteQueueSize)]: 0,
  [Symbol(timeout)]: null,
  [Symbol(kBuffer)]: null,
  [Symbol(kBufferCb)]: null,
  [Symbol(kBufferGen)]: null,
  [Symbol(kCapture)]: false,
  [Symbol(kBytesRead)]: 0,
  [Symbol(kBytesWritten)]: 0
}
May 08 13:40:21.297 [notice] Tor 0.4.4.6 (git-2a8b789ea6f308d0) running on Windows 8 [or later] with Libevent 2.1.11-stable, OpenSSL 1.1.1h, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
May 08 13:40:21.297 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning

May 08 13:40:21.319 [notice] Read configuration file "C:\Users\IEUser\AppData\Roaming\Zbay\torrc".

May 08 13:40:21.320 [warn] Path for GeoIPFile (<default>) is relative and will resolve to C:\Users\IEUser\AppData\Local\Programs\zbay\<default>. Is this what you wanted?
May 08 13:40:21.320 [warn] Path for GeoIPv6File (<default>) is relative and will resolve to C:\Users\IEUser\AppData\Local\Programs\zbay\<default>. Is this what you wanted?

May 08 13:40:21.321 [warn] ControlPort is open, but no authentication method has been configured.  This means that any program on your computer can reconfigure your Tor.  That's bad!  You should upgrade your Tor controller as soon as possible.

May 08 13:40:21.324 [notice] Opening Socks listener on 127.0.0.1:9050
May 08 13:40:21.325 [notice] Opened Socks listener on 127.0.0.1:9050
May 08 13:40:21.325 [notice] Opening Control listener on 127.0.0.1:9151

May 08 13:40:21.325 [notice] Opened Control listener on 127.0.0.1:9151

data is 250 OK

entered this.connect
data is 250 OK

data is 250 closing connection

connection ended
dataaa 250 OK

<ref *1> Socket {
  connecting: true,
  _hadError: false,
  _parent: null,
  _host: 'localhost',
  _readableState: ReadableState {
    objectMode: false,
    highWaterMark: 16384,
    buffer: BufferList { head: null, tail: null, length: 0 },
    length: 0,
    pipes: [],
    flowing: null,
    ended: false,
    endEmitted: false,
    reading: false,
    sync: true,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    errorEmitted: false,
    emitClose: false,
    autoDestroy: false,
    destroyed: false,
    errored: null,
    closed: false,
    closeEmitted: false,
    defaultEncoding: 'utf8',
    awaitDrainWriters: null,
    multiAwaitDrain: false,
    readingMore: false,
    decoder: null,
    encoding: null,
    [Symbol(kPaused)]: null
  },
  _events: [Object: null prototype] { end: [Function: onReadableStreamEnd] },
  _eventsCount: 1,
  _maxListeners: undefined,
  _writableState: WritableState {
    objectMode: false,
    highWaterMark: 16384,
    finalCalled: false,
    needDrain: false,
    ending: false,
    ended: false,
    finished: false,
    destroyed: false,
    decodeStrings: false,
    defaultEncoding: 'utf8',
    length: 0,
    writing: false,
    corked: 0,
    sync: true,
    bufferProcessing: false,
    onwrite: [Function: bound onwrite],
    writecb: null,
    writelen: 0,
    afterWriteTickInfo: null,
    buffered: [],
    bufferedIndex: 0,
    allBuffers: true,
    allNoop: true,
    pendingcb: 0,
    prefinished: false,
    errorEmitted: false,
    emitClose: false,
    autoDestroy: false,
    errored: null,
    closed: false,
    closeEmitted: false,
    writable: true
  },
  allowHalfOpen: false,
  _sockname: null,
  _pendingData: null,
  _pendingEncoding: '',
  server: null,
  _server: null,
  [Symbol(async_id_symbol)]: 110,
  [Symbol(kHandle)]: TCP {
    reading: false,
    onconnection: null,
    [Symbol(owner_symbol)]: [Circular *1]
  },
  [Symbol(kSetNoDelay)]: false,
  [Symbol(lastWriteQueueSize)]: 0,
  [Symbol(timeout)]: null,
  [Symbol(kBuffer)]: null,
  [Symbol(kBufferCb)]: null,
  [Symbol(kBufferGen)]: null,
  [Symbol(kCapture)]: false,
  [Symbol(kBytesRead)]: 0,
  [Symbol(kBytesWritten)]: 0
}
data is 250 OK

entered this.connect
data is 250 OK

data is 250 closing connection

connection ended
dataaa 250 OK

<ref *1> Socket {
  connecting: true,
  _hadError: false,
  _parent: null,
  _host: 'localhost',
  _readableState: ReadableState {
    objectMode: false,
    highWaterMark: 16384,
    buffer: BufferList { head: null, tail: null, length: 0 },
    length: 0,
    pipes: [],
    flowing: null,
    ended: false,
    endEmitted: false,
    reading: false,
    sync: true,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    errorEmitted: false,
    emitClose: false,
    autoDestroy: false,
    destroyed: false,
    errored: null,
    closed: false,
    closeEmitted: false,
    defaultEncoding: 'utf8',
    awaitDrainWriters: null,
    multiAwaitDrain: false,
    readingMore: false,
    decoder: null,
    encoding: null,
    [Symbol(kPaused)]: null
  },
  _events: [Object: null prototype] { end: [Function: onReadableStreamEnd] },
  _eventsCount: 1,
  _maxListeners: undefined,
  _writableState: WritableState {
    objectMode: false,
    highWaterMark: 16384,
    finalCalled: false,
    needDrain: false,
    ending: false,
    ended: false,
    finished: false,
    destroyed: false,
    decodeStrings: false,
    defaultEncoding: 'utf8',
    length: 0,
    writing: false,
    corked: 0,
    sync: true,
    bufferProcessing: false,
    onwrite: [Function: bound onwrite],
    writecb: null,
    writelen: 0,
    afterWriteTickInfo: null,
    buffered: [],
    bufferedIndex: 0,
    allBuffers: true,
    allNoop: true,
    pendingcb: 0,
    prefinished: false,
    errorEmitted: false,
    emitClose: false,
    autoDestroy: false,
    errored: null,
    closed: false,
    closeEmitted: false,
    writable: true
  },
  allowHalfOpen: false,
  _sockname: null,
  _pendingData: null,
  _pendingEncoding: '',
  server: null,
  _server: null,
  [Symbol(async_id_symbol)]: 129,
  [Symbol(kHandle)]: TCP {
    reading: false,
    onconnection: null,
    [Symbol(owner_symbol)]: [Circular *1]
  },
  [Symbol(kSetNoDelay)]: false,
  [Symbol(lastWriteQueueSize)]: 0,
  [Symbol(timeout)]: null,
  [Symbol(kBuffer)]: null,
  [Symbol(kBufferCb)]: null,
  [Symbol(kBufferGen)]: null,
  [Symbol(kCapture)]: false,
  [Symbol(kBytesRead)]: 0,
  [Symbol(kBytesWritten)]: 0
}
data is 250 OK

entered this.connect
data is 250-ServiceID=qcdykalu76an3itoj75fbv5kiz2dm62rcysglgno4wf2r2mmgnqsreqd
250 OK

data is 250 closing connection

connection ended
dataaa 250-ServiceID=qcdykalu76an3itoj75fbv5kiz2dm62rcysglgno4wf2r2mmgnqsreqd
250 OK

<ref *1> Socket {
  connecting: true,
  _hadError: false,
  _parent: null,
  _host: 'localhost',
  _readableState: ReadableState {
    objectMode: false,
    highWaterMark: 16384,
    buffer: BufferList { head: null, tail: null, length: 0 },
    length: 0,
    pipes: [],
    flowing: null,
    ended: false,
    endEmitted: false,
    reading: false,
    sync: true,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    errorEmitted: false,
    emitClose: false,
    autoDestroy: false,
    destroyed: false,
    errored: null,
    closed: false,
    closeEmitted: false,
    defaultEncoding: 'utf8',
    awaitDrainWriters: null,
    multiAwaitDrain: false,
    readingMore: false,
    decoder: null,
    encoding: null,
    [Symbol(kPaused)]: null
  },
  _events: [Object: null prototype] { end: [Function: onReadableStreamEnd] },
  _eventsCount: 1,
  _maxListeners: undefined,
  _writableState: WritableState {
    objectMode: false,
    highWaterMark: 16384,
    finalCalled: false,
    needDrain: false,
    ending: false,
    ended: false,
    finished: false,
    destroyed: false,
    decodeStrings: false,
    defaultEncoding: 'utf8',
    length: 0,
    writing: false,
    corked: 0,
    sync: true,
    bufferProcessing: false,
    onwrite: [Function: bound onwrite],
    writecb: null,
    writelen: 0,
    afterWriteTickInfo: null,
    buffered: [],
    bufferedIndex: 0,
    allBuffers: true,
    allNoop: true,
    pendingcb: 0,
    prefinished: false,
    errorEmitted: false,
    emitClose: false,
    autoDestroy: false,
    errored: null,
    closed: false,
    closeEmitted: false,
    writable: true
  },
  allowHalfOpen: false,
  _sockname: null,
  _pendingData: null,
  _pendingEncoding: '',
  server: null,
  _server: null,
  [Symbol(async_id_symbol)]: 148,
  [Symbol(kHandle)]: TCP {
    reading: false,
    onconnection: null,
    [Symbol(owner_symbol)]: [Circular *1]
  },
  [Symbol(kSetNoDelay)]: false,
  [Symbol(lastWriteQueueSize)]: 0,
  [Symbol(timeout)]: null,
  [Symbol(kBuffer)]: null,
  [Symbol(kBufferCb)]: null,
  [Symbol(kBufferGen)]: null,
  [Symbol(kCapture)]: false,
  [Symbol(kBytesRead)]: 0,
  [Symbol(kBytesWritten)]: 0
}
data is 250 OK

entered this.connect
data is 250-ServiceID=cbazpcag3pv5ea47oq3pyuyhrf6kim5v6lylv7jkvkgmkrohze4t34yd
250 OK

data is 250 closing connection

connection ended
dataaa 250-ServiceID=cbazpcag3pv5ea47oq3pyuyhrf6kim5v6lylv7jkvkgmkrohze4t34yd
250 OK

Checking for update
Server running on port 4677
websocket connected
connection ready wchodzi
local address: /dns4/qcdykalu76an3itoj75fbv5kiz2dm62rcysglgno4wf2r2mmgnqsreqd.onion/tcp/7950/ws/p2p/QmNb2svob5vUXc55xhiAbr52En72pxpw9FdzotTK2e3Wws
bootstrapMultiaddrs: [
  '/dns4/2lmfmbj4ql56d55lmv7cdrhdlhls62xa4p6lzy6kymxuzjlny3vnwyqd.onion/tcp/7788/ws/p2p/Qmak8HeMad8X1HGBmz2QmHfiidvGnhu6w6ugMKtx8TFc85'
]
1
creating channels count
ALL CHANNELS COUNT: 12
ALL CHANNELS COUNT: [
  'zs10zkaj29rcev9qd5xeuzck4ly5q64kzf6m6h9nfajwcvm8m2vnjmvtqgr0mzfjywswwkwke68t00',
  'zs19n59plvpzcysmugyck79kmzzzrk3gqmewm3u8qj38s4wlcnaw0sqp0qtvqwagryg4prtuakzmg3',
  'zs1rljm74uefpfp6aqxdyfy04p35yh8lclg3d67s0240dc7mhkhws7d47mcydykgkgwnvf9chjelcq',
  'zs1dtpp4f8scu847l3mcnuhgefdq8vtx5vpay3duvfw7zesrcsqc0v3jw84vc2xkt97yny0yut3ykg',
  'zs1r58tmaur7sgg07tnz0dld2l0ag6ztkx26f70xl2pedhv4m6auw653pyjnhwrphq2jfmmvqghkkd',
  'zs1snhzdc6u27lkhzn5ufx9hr685m5xlad4k23kp3cxmsruhcrpufamy35swuqax6yq608sjhlrq8t',
  'zs18fx34c4uhdhsq4eyappx026jpks3rpdw62qm853djklxepp9ullrfy7mhyw6s3968fsgc5hapk9',
  'zs1ppz4qxctnv85ycex7u4cyxatz2wnduzy7usvyagma6h45lwrx88pdl3mdu25z763uvfy7a0qpfs',
  'zs15tr7xar3c4pvqr39cy7sl3qepgm4hmvlak7kndx83ff6fm3xmvvzlr0t6n9pcwp3nxndkvwgtwp',
  'zs1pmy764s78y40qs4jm2vjd8xxlxxw8x7ec0hf7237p53h47ekgjvex0jfqey4ggy9l0luxlt29ah',
  'zs1hj2ypw43n904lwfmw7jcyfm0656qjk3k0839rwyn56wq238cdd3k86xjl9d6sj0afngust83lzk',
  'zs1xefznfdf00uvgyddrwxmwmag04t6nm5vuna8geuanr055ezyqufkmkrs3kcal2thvfmrgjch7ua'
]
2
created or initialized database
before loading database
after laoding database
ALL USERS COUNT: 12
ALL USERS COUNT: [
  '03cc3b818563dab791acc265af9f9693d9ff925df878d62e4ea1c80e05650e033f',
  '032da3d0baa9aae960f74a04cbc11a2b4e10afaade5f54b34fcf179c5828553cde',
  '02dc8264c555d46b3f6b16f1e751e979ebc69e6df6a02e7d4074a5df981e507da2',
  '03abd60127a15f331c0ff436d369ed2802f9343abcfe515196ed35b4083139197f',
  '03cd89a555f48c4e7a054004e7212b4e379013e755d42722f24f18f4cdc86a7b27',
  '02ab5a24b67c2e4ed83e48ca21deb01d6c3ebc550c59e5aa819dafb7adca417396',
  '02a1933e9a092c86bd1042b8e3edbe791a65c377e27216a1edd9ea22531f23849e',
  '032f1e9a32d702319b9d38cb696eeb4c46e3a115dea8c047905beefb260fa56e47',
  '03a089ac8d65c2d879921645e0dc25fdc99e80b7098621cd2c2338f27ff9c73b81',
  '039675d9b7b1352667556f7403caaa726209100be21ff7502a613c0837caa5738b',
  '036c7eae5c393e5028af4eedbd795305ef514f56f2a1d488d4e882e67d69188bad',
  '0217c1dc275332a6c962e6e4f7baa8572bcbd9dd8c3a602d84b43237d00c514bf8'
]
3
try to create db for messages
ALL MESSAGE THREADS COUNT: 9
ALL MESSAGE THREADS COUNT: [
  '30f3faf474f5b1220ced225823a275d2371ad7ea50d801499b35827af49c7545',
  '8ba4c9c4cc2f292546a849fb88a4abc2b6cbe00f26a9e1ebf03741803c3fce47',
  '2722db923b136c6374adf20594ce2ed7173163562cbb5939c560ce871e143bcf',
  '709e511e55aa0f0b079896de4374c63d2bbd643e2a73595364c9305c6d98c3f5',
  '4d40aae1424824ddc969c21caaf713e655058943b79a7d5be0c6d7e850fab925',
  '112e43ad3db86724b4038493d7323908f4b3894c213ceb4be7cc2d636119521c',
  '8f0a0508b222c6b3659b65d66059670c1e006e9f244c061afee27c80ce2f06d7',
  '561dd0c987779204b242d1ff2d9f95fc09d99083272170cf3ffc81504d35995d',
  '2b5767e0aa31e7a3eb5bcef1798f41c3f12c9da572fd3db6942e4dc818c0091d'
]
4
Update for version 3.2.11-zbay-lite is not available (latest version: 3.2.11-zbay-lite, downgrade is disallowed).
Checking for update
checking for updates...
Update for version 3.2.11-zbay-lite is not available (latest version: 3.2.11-zbay-lite, downgrade is disallowed).
event no update
initAllChannels: 1.709s
5
Subscribing to channel  zs10zkaj29rcev9qd5xeuzck4ly5q64kzf6m6h9nfajwcvm8m2vnjmvtqgr0mzfjywswwkwke68t00
Subscription to channel ready zs10zkaj29rcev9qd5xeuzck4ly5q64kzf6m6h9nfajwcvm8m2vnjmvtqgr0mzfjywswwkwke68t00
STORAGE: getAvailableUsers entered
STORAGE: getPrivateConversations enetered
STORAGE: getAvailableUsers [object Object]
STORAGE: getPrivateConversations payload payload
Connected to Qmak8HeMad8X1HGBmz2QmHfiidvGnhu6w6ugMKtx8TFc85
Connected to QmVaVtzmakUYgjSxsmdQGjUEb68fEuYjCrv1zi2pPvx5Eg
Connected to Qmb9WDZUnUzEmZwkbMMGi4cV65F1sqcQa49dfZy9baRBJo
```

Logs seem to go abruptly silent at this point. The UI is still responsive but it's possible that some part of the app is just crashed. 

When I quit, I see absolutely nothing of interest in Powershell. Nothing is logged. Zbay processes are still running in Powershell. 

<img width="1702" alt="image" src="https://user-images.githubusercontent.com/213678/117548605-ddf2cf00-b003-11eb-9741-a9ef458f3032.png">

**Comment by holmesworcester** [comment]
When we check in Sysinternals we can see that the processes that shut down successfully on Zbay quit are:

* Renderer
* Tor.exe

The ones that do not are:

* Network
* Audio
* GPU

You can see a similar problem here: https://stackoverflow.com/questions/52105917/electron-windows-app-close-not-ending-threads 

Tor is quit on shutdown in the handler for the Electron event `before-quit` The fact that Tor is getting quit means that this handler is working. But it seems that the app.quit() event never gets called.

**Comment by holmesworcester** [comment]
So I've been trying to get a Windows development environment up and running, and it seems like our instructions for Windows are not adequate—at least not for the [free, Microsoft-provided Windows 10 VM](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/).

To get it working, I had to:

* Remove package-lock.json
* (I think) npm install --global windows-build-tools 
* Run powershell as administrator (which is probably obvious, but just noting it here since the error wasn't clear that this was the problem.)

At the moment, I'm stuck on this issue, where gyp is trying to download a 32-bit version of node-webrtc that does not exist, even though Windows says it's 64-bit. I posted the following question to the node-webrtc project, where it seems someone else had a similar issue: https://github.com/node-webrtc/node-webrtc/issues/670

**Comment by holmesworcester** [comment]
Tried deleting `node_modules` and importing `index.node` from the release version of Zbay. Still ran into problems:

```
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\IEUser\\Documents\\GitHub\\ZbayLite\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\IEUser\Documents\GitHub\ZbayLite\node_modules\ipfs-bitswap\node_modules\secp256k1
gyp ERR! node -v v14.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

Created https://github.com/ZbayApp/zbay/issues/812 to resolve windows dev environment instructions.
