### ISSUE TITLE
JS error when responding to an anon user.

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/zbay#828]
Steps to reproduce:

1. Create an account.
2. DM another Zbay
3. In that other Zbay, try to reply.

Expected: it works
Actual: javascript error. 

```
TypeError: Cannot read property 'length' of undefined
    at eval (webpack-internal:///./src/renderer/zbay/messages.js:429:35)
    at step (webpack-internal:///./src/renderer/zbay/messages.js:83:23)
    at Object.eval [as next] (webpack-internal:///./src/renderer/zbay/messages.js:64:53)
    at eval (webpack-internal:///./src/renderer/zbay/messages.js:58:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///./src/renderer/zbay/messages.js:54:12)
    at Object.messageToTransfer (webpack-internal:///./src/renderer/zbay/messages.js:424:12)
    at eval (webpack-internal:///./src/renderer/store/handlers/channel.ts:391:90)
    at step (webpack-internal:///./src/renderer/store/handlers/channel.ts:83:23)
    at Object.eval [as next] (webpack-internal:///./src/renderer/store/handlers/channel.ts:64:53)
```

**Comment by kingalg** [comment]
It is working in my v 3.2.14.
